version: "3.8"
name: web_hw13_app
services:
  redis:
    image: redis:alpine
    expose:
      - "${REDIS_PORT}"
  pg:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  code :
    build: app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - app/.env-prod
    depends_on:
      - pg
      - redis
    healthcheck:
      test: ["CMD", "curl","-f","-X","GET","http://localhost:${APP_PORT}/api/healthchecker","-H","accept: application/json", "||", "exit", "1" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s